# Generated by Django 3.0.5 on 2020-10-15 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_api', '0005_ordercreate_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderconfirmation',
            name='order_create',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='django_rest_api.OrderCreate'),
        ),
    ]
